version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    build: ./gateway-dotnet
    ports:
      - "5000:5000"
    depends_on:
      - datamanager
    networks:
      - iotnet

  datamanager:
    build: ./datamanager-py
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - iotnet

networks:
  iotnet:

volumes:
  pgdata:
