version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - iotnet

  datamanager:
    build: ./datamanager-py
    env_file:
      - datamanager-py/.env
    environment:
      POSTGRES_HOST: postgres        # pregazi localhost iz .env kad je u dockeru
    # ports nisu obavezni za inter-container, ali ih ostavljamo da možeš test sa hosta
    ports:
      - "50051:50051"                # tvoja app sluša na 50051
    depends_on:
      - postgres
    networks:
      - iotnet

  gateway:
    build:
      context: .
      dockerfile: ./gateway-dotnet/Dockerfile
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      Grpc__TelemetryServiceUrl: "http://datamanager:50051"  # KLJUČNO
    ports:
      - "5000:8080"
    depends_on:
      - datamanager
    networks:
      - iotnet

networks:
  iotnet:
    driver: bridge

volumes:
  pgdata:
